name: quant
channels:
  - anaconda
  - defaults
dependencies:
  - blas
  - bottleneck
  - bzip2
  - ca-certificates
  - libcxx
  - libffi
  - libgfortran5
  - libopenblas
  - llvm-openmp
  - ncurses
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - pandas
  - pip
  - pyparsing
  - python
  - python-dateutil
  - pytz
  - readline
  - setuptools
  - six
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
      - aiohttp
      - aiosignal
      - alpha-vantage
      - async-timeout
      - attrs
      - blinker
      - certifi
      - charset-normalizer
      - click
      - flask
      - frozenlist
      - gunicorn
      - idna
      - itsdangerous
      - jinja2
      - markupsafe
      - multidict
      - packaging
      - patsy
      - requests
      - scipy
      - statsmodels
      - stocktrends
      - urllib3
      - werkzeug
      - yarl
